#!/usr/bin/env bash

set -o errexit
set -o pipefail
# set -o xtrace

__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" # Directory where this script exists.
__root="$(cd "$(dirname "${__dir}")" && pwd)"         # Root directory of project.

BUILD_ID=${BUILD_ID:-"r0"}
BUILD_DATE=$(date -u +"%y%m%d")
APP_VERSION="${APP_VERSION:-"${BUILD_DATE}-${BUILD_ID}"}"

GIT_REV=${BUILD_HASH:-"0000000000000000000000000000000000000000"}
GIT_DIRTY="false"
if [ -z "$BUILD_HASH" ] && [ $(git rev-parse --is-inside-work-tree) ]; then
	GIT_REV=$(git rev-parse HEAD)
	GIT_DIRTY=$([ -n "$(git status --porcelain)" ] && echo "true" || echo "false")
fi

cd "$__root/cmd/version"

# Written the way gofmt would write it. The gate runs `gofmt -l .` from the
# root, so a generated file that is merely close fails the whole run on a file
# nobody typed -- which is what `func init(){` and the aligned `=` used to do,
# every time somebody ran `go generate ./...` before `./scripts/test.sh`.
(cat | tee ./version.g.go) <<EOL
// Code generated by scripts/gen-version-file.sh. DO NOT EDIT.
package version

func init() {
	b := &build_info
	b.Version = "$APP_VERSION"
	b.GitRev = "$GIT_REV"
	b.GitDirty = $GIT_DIRTY
}
EOL
